export const texts = {
  dashboard: {
    title: 'Dashboard',
    charts: {
      chartTitle: 'Despesas por Categoria',
      chartPlaceholder: 'Gráfico será implementado',
    },
    currentBalance: 'Saldo Atual',
    income: 'Receitas',
    expenses: 'Despesas',
  },
  transaction: {
    register: {
      title: 'Cadastrar Movimentação',
      transactionTitle: 'Título',
      transactionTitlePlaceholder: 'Digite um título para a transação...',
      value: 'Valor',
      valuePlaceholder: 'R$ 0,00',
      type: 'Tipo',
      income: 'Receita',
      expense: 'Despesa',
      category: 'Categoria',
      categories: {
        food: 'Alimentação',
        transport: 'Transporte',
        entertainment: 'Entretenimento',
        health: 'Saúde',
        other: 'Outros',
      },
      paymentMethod: 'Forma de Pagamento',
      paymentMethods: {
        cash: 'Dinheiro',
        credit: 'Cartão de Crédito',
        debit: 'Cartão de Débito',
        pix: 'PIX',
      },
      date: 'Data',
      description: 'Descrição (Opcional)',
      descriptionPlaceholder: 'Digite uma descrição para a transação...',
      save: 'Salvar',
      validation: {
        titleRequired: 'O título é obrigatório',
        amountRequired: 'O valor é obrigatório',
        amountGreaterThanZero: 'O valor deve ser maior que zero',
        typeRequired: 'O tipo é obrigatório',
        categoryRequired: 'A categoria é obrigatória',
        paymentMethodRequired: 'A forma de pagamento é obrigatória',
        dateRequired: 'A data é obrigatória',
      },
    },
  },
}
